### ISSUE TITLE
[Features] Alert if the segment has -100 as id

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/WME-send-to-slack#10]
**Is your feature request related to a problem? Please describe.**
When a request is sent by a new editor that has created a new segment but not saved it, the link is sent but -101 is used as ID, that is not working

**Describe the solution you'd like**
Add an alert if the id is -100

**Comment by tunisiano187** [comment]
Still relevant, missing time

**Comment by tunisiano187** [comment]
Yes

Le jeu. 23 juil. 2020 à 11:51, stale[bot] <notifications@github.com> a
écrit :

**Comment by tunisiano187** [comment]
Still interesting... the bot shouldn't have closed it...

**Comment by ordonezgs** [comment]
Isn't this already implemented?
https://github.com/tunisiano187/WME-send-to-slack/blob/e9ae8503df562ae9683213d8bb4d4a4ac1df0419/WME-send-to-slack.user.js#L460-L463

**Comment by tunisiano187** [comment]
It seems still having problems
you can test by creating a new segment and trying to send it as a lock
request, but i think it doesn't show any error...

**Comment by tunisiano187** [comment]
OK, seems working now
