### ISSUE TITLE
[Bug] GForm not allowing Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by BertZZZZ** [tunisiano187/WME-send-to-slack#11]
**Describe the bug**
The google sheet "WME-send-to-slack (réponses)" did not receive data since 19-4-2020

Has it moved or is there a bug?
Tx

**Comment by tunisiano187** [comment]
It seems Google does not allow the action from athother website... 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
I think i'll need to rewrite that part to use their APIs, but i didn't had use them, so i need to read...

**Comment by BertZZZZ** [comment]
Hey Fabian
Sorry, I did wrongly describe the bug:  There is data after 19/4/20 - but the editors level is removed/missing.  Causing my filters to... filter.
![image](https://user-images.githubusercontent.com/28437379/85675792-4ecc1980-b6c6-11ea-9742-948975a9e347.png)
Was the level removed, or can we not access it anymore?
I'll backfill the data for now - guess that you can fix?

**Comment by tunisiano187** [comment]
OK, i'll take a look into it, that's weird because the message seems to tell it's forbiden...

**Comment by tunisiano187** [comment]
Should be solved in 2020.06.28.01, don't hesitate to reopen it if the problem isn't solved
