### ISSUE TITLE
[Bug] after accepting to cancel, script does not accept sending

### ISSUE THREAD

**Issue by yvesg54** [tunisiano187/WME-send-to-slack#13]
**Describe the bug**
Once I accept to cancel, the script does not send to slack anymore.

**To Reproduce**
je demande lock sur un segment, et je laisse niveau de lock par défaut, <=4 (mon niveau = 4)
le script me prévient que c'est inutile, et je cancel, tout s’arrête, tb.
je refais une demande sur même segment, je corrige le niveau de lock, je donne la raison, clique OK: le script n'envoie pas, et me prévient en rouge qu'il n'envoie pas.
le script fonctionne bien après refresh de la fenêtre.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 23
 - Version script  2020.06.22.02
 - TamperMonkey 

**Additional context**

**Comment by tunisiano187** [comment]
Should be solved
