### ISSUE TITLE
[Features] Follow updates of WazeWrap automatically

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/WME-send-to-slack#15]
**Is your feature request related to a problem? Please describe.**
It could be ineresting to automatically update the link to WazeWrap if the script is updated

**Describe the solution you'd like**
Follow the WazeWrap git and update it automatically

**Comment by justins83** [comment]
What is the point of this? You should never need to update the link to WazeWrap

**Comment by tunisiano187** [comment]
The Goal is ti have the latest version (date at the end) to have your updates directly (usage of your variables for example when Waze make some changes on the W var) that will "force" the update

**Comment by justins83** [comment]
This is not necessary. WazeWrap updates without needing to change the
installed script so there is no need to monitor for it's changes.

**Comment by tunisiano187** [comment]
OK,  i thougt because a see some script pushing a new version to force Wazewrap to update... (in their explaination)

**Comment by justins83** [comment]
That is very rare - only when I have to change where the WazeWrap implementation file pulls from.

**Comment by tunisiano187** [comment]
OK thanx for the followup
