### ISSUE TITLE
[Features] Translation

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/WME-send-to-slack#21]
Currently only in english

That could be interesting to have it translated with the help of the community

Create a function that will take the message in the language of the i18n (https://greasyfork.org/fr/scripts/18927-wme-rtc-improvements/code) good example

Create a link (only for the Localizators (listed in WMESTSData) anf if pushed send them to a Form with most fields alreday completed for them to ask for add a new translation until i found the spreadcheat solution

**Comment by ordonezgs** [comment]
Implemented please close the issue as I'm not able dut to permissions

**Comment by tunisiano187** [comment]
Done thank you @ordonezgs
