### ISSUE TITLE
[Bug] WazeWrap error in Localization()

### ISSUE THREAD

**Issue by ordonezgs** [tunisiano187/WME-send-to-slack#29]
Let's look a way to verify the WazeWrap load, because in this part of the script inside the conditional I'm unable to call for a WazeWrap alert error due to the unfinished load of the WazeWrap

Line 257 of V2020.07.17.02:
https://github.com/tunisiano187/WME-send-to-slack/blob/b3478d18be3159b972808b72f63a226da69c6430/WME-send-to-slack.user.js#L257

**Comment by justins83** [comment]
It would help to read the WazeWrap documentation **at all**, or look at any of the scripts that use WazeWrap.  You should have a bootstrap and be checking WazeWrap.Ready before initializing the script.

**Comment by tunisiano187** [comment]
Found WazeWrap.Ready, i'll try to implement it

**Comment by tunisiano187** [comment]
@justins83 , just understood my problem with the forum, my connection often disconnect, so never seen the first part... My bad.
Thank you

**Comment by tunisiano187** [comment]
https://www.waze.com/forum/viewtopic.php?f=819&t=210961&hilit=wazewrap

**Comment by tunisiano187** [comment]
Script breaks when using the WazeWrap Alerts, will continue to search how to implement it another way

**Comment by ordonezgs** [comment]
Solved
