### ISSUE TITLE
[Bug] Legacy WebHook Slack Migration

### ISSUE THREAD

**Issue by ordonezgs** [tunisiano187/WME-send-to-slack#38]
https://github.com/tunisiano187/WME-send-to-slack/blob/8d6472a574e9618a9a50a896e52fb5c55c993dc3/WME-send-to-slack.user.js#L538-L555

Not sure if the script is working well in Slack, because of this documentation talking about:
_You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration._

Please check Legacy Docs:
https://api.slack.com/legacy/custom-integrations/incoming-webhooks
and Up-to-Date Slack WebHook Documentation:
https://api.slack.com/messaging/webhooks

**Comment by tunisiano187** [comment]
Yes it works correctly,
that's just the only solution to have the same webhook everywhere.
It can be a webhook by channel, but currently it works perfectly that way.

**Comment by ordonezgs** [comment]
[No Progress] [Documentation] Tags
