### ISSUE TITLE
[Bug] Autolock doesn't work anymore

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/WME-send-to-slack#39]
**Describe the bug**
When an editor ask for lock the script was making the work (not saving) for the reviewer (helps for mobile), it's not anymore

**To Reproduce**
an editor needs to ask for lock : (&wmestslock=x in the url)
The script should change the lock level to the one requested

**Comment by ordonezgs** [comment]
I have a pending fix for this. I will wait for the next update to create the pull request, because of the not working STSData require file in the script.

**Comment by ordonezgs** [comment]
It was related to #29, after that fix, that functionality was gone.

**Comment by tunisiano187** [comment]
It seems that it was due to a timeout, I've removed the part of the script
where it was sending all js errors to the console with (one of your
scripts, ... and it seems ok now.
for the WMESTSData, don't forget to change the date at the end of the
require line, it will load the new one

Le sam. 25 juil. 2020 à 03:54, ordonezgs <notifications@github.com> a
écrit :

**Comment by ordonezgs** [comment]
Do you mind check again?

For me stills not working. It doesn't even loads the actions tab (in my solution or we can call it enhacement it also don't load but it works well) but when I deselect the segment and select any or the same segment it works.

It would be a problem with multiple segments at this point since I have to deselect and re-select the desired segments.

Another [BUG] related to this is the impossibility to undo the change of the auto upper level thing (which I have also solved in my proposed solution).

**Comment by tunisiano187** [comment]
Not able to undo?
the undo of the WME works for me.

The main problem of this issue is the load time, if it is too high, it
doesn't set the level.
i think at the end of the load of the we should force a check of selected
thing, but...

Le ven. 31 juil. 2020 à 22:53, ordonezgs <notifications@github.com> a
écrit :

**Comment by ordonezgs** [comment]
For me isn't working. The undo thing is that every time I press it, it remains re auto locking it, so it undo but re do in some way.

Let me try my solution I think it also waits for the load to complete.

Maybe the undo thing might be a cross script incompatibility but not sure, need to investigate.

**Comment by ordonezgs** [comment]
Re opened. This is due to WME design change. Related to #84

**Comment by tunisiano187** [comment]
Indeed, I'll try to fix it too

**Comment by tunisiano187** [comment]
Should work with this version, don't hesitate to reopen if not

**Comment by ordonezgs** [comment]
This is still not working for me
![image](https://user-images.githubusercontent.com/17103864/175698664-5806e84b-96d7-4d82-b149-d67d0f8eeb6d.png)

**Comment by tunisiano187** [comment]
Can you give me the link used? maybe it's a special case, i've tested on POI, segment and radar, it seems OK

**Comment by tunisiano187** [comment]
Still broken

Le sam. 15 oct. 2022 à 23:39, stale[bot] ***@***.***> a
écrit :

**Comment by ordonezgs** [comment]
Fixed with #133 

Known bug: AutLock works first than TranslationsInfo so, no strings are loaded for this. Just in case we need an advice for this feature.
