### ISSUE TITLE
Add V and X on UR's to ask for close as Solved or not identified

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/WME-send-to-slack#4]
Change the options to "request to <br />solve" and "request to close as <br/>not identified" on UR's to ask for close as Solved or not identified

**Comment by Hipska** [comment]
Do you need help on this?

**Comment by tunisiano187** [comment]
Every help is welcome, I just don't have much time currently.
But feel free to help if you want.

Thank you

Le mer. 1 juil. 2020 à 13:25, Thomas Casteleyn <notifications@github.com> a
écrit :

**Comment by Hipska** [comment]
Yes it's still relevant since it's simply not implemented yet.

**Comment by tunisiano187** [comment]
Yes

Le ven. 31 juil. 2020 à 14:12, stale[bot] <notifications@github.com> a
écrit :

**Comment by Hipska** [comment]
Maybe disable that bot for this repo? It doesn't add any value..

**Comment by tunisiano187** [comment]
That's to avoid letting things forgotten

**Comment by Uwe4Waze** [comment]
Info: The above link ("Merge pull request no. 4 from Uwe4Waze/fix-missing-validation-icon] ...) does not reference this issue.

**Comment by ordonezgs** [comment]
I've made a Milestone in beta,

It left to implement the buttons (front-end things... - may ask for some help here? ) and then make that `construct()` will be able to handle the request.

Refer to:
https://github.com/tunisiano187/WME-send-to-slack/blob/70473476f08d28cfbf5904d1ed6dbe82a24a4bdf/WME-send-to-slack.user.js#L252

Then something similar to:
https://github.com/tunisiano187/WME-send-to-slack/blob/70473476f08d28cfbf5904d1ed6dbe82a24a4bdf/WME-send-to-slack.user.js#L253-L256
But with the new `PANEL_WITH_UR`

**Comment by ordonezgs** [comment]
> Change the options to "request to solve" and "request to close as not identified" on UR's to ask for close as Solved or not identified

Postponed to a later fix...
