### ISSUE TITLE
[Features] Map Comment Validation

### ISSUE THREAD

**Issue by ordonezgs** [tunisiano187/WME-send-to-slack#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For me at least it isn't necessary to have the button of validation into a map comment.

**Describe alternatives you've considered**
Create a conditional for this map comments.

**Additional context**
I can't Image in which manner you can validate a map comment.

**Comment by tunisiano187** [comment]
Is it really important to remove it?
i prefer letting it, maybe someone will use it for another thing...

Le ven. 31 juil. 2020 à 22:58, ordonezgs <notifications@github.com> a
écrit :

**Comment by ordonezgs** [comment]
It's ok. Just asking.
