### ISSUE TITLE
[Bug] Blocks RTC

### ISSUE THREAD

**Issue by markrsmith83** [tunisiano187/WME-send-to-slack#49]
** add an X into between the [ ] like this [X] if you've tryied
[X ] I've tryied to disable every other scripts
[X ] I've updated the Browser
[ X] I've updated Tampermonkey/GreaceMonkey
[ X] I've updated the script to the latest

**Describe the bug**
When WME Send to Slack is active, The "Add Closure" button is blocked on the Road Closures tab for a segment. This prevents the ability to enter RTC. This seems to happen on the SECOND attempt to enter a RTC per Chrome app session.
**To Reproduce**
1. Enable WME Send to Slack. 
2. Select a segment
3. Go to Road Closures tab
4. If available, click Add Closure.
5. Abandon the entry and go back to map.
6. Select a segment again.
7. Go to Road Closures tab.
8. The Add Closure button is missing.
**Expected behavior**
The Add Closure button should always be available.
**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Catalina 10.15.6
 - Browser [e.g. chrome, safari] Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - Version [e.g. 22] Send to Slack 2020.08.08.03
 - TamperMonkey

**Comment by tunisiano187** [comment]
indeed, but the button is hidden (a scroll get it back)
I'll try to find a solution.
Thank you

Le sam. 12 sept. 2020 à 19:54, markrsmith83 <notifications@github.com> a
écrit :

**Comment by tunisiano187** [comment]
It solved.
it will be published soon

Thank you

Note : It's linked to the PR #50

**Comment by tunisiano187** [comment]
Not completely working

**Comment by tunisiano187** [comment]
Completely solved in https://github.com/tunisiano187/WME-send-to-slack/commit/0e54d2d5b09afcf774f9d904a9dc045a5c70a187
