### ISSUE TITLE
[Bug] WME design change, locks and validation icons are missing and settings tab not showing.

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/WME-send-to-slack#84]
Locks are back with: https://github.com/tunisiano187/WME-send-to-slack/commit/0a816f42ed43e75f808eb9b2dd9bb8f6d6dd1936

**Comment by tunisiano187** [comment]
2022.06.22.02 solve missing locks

**Comment by tunisiano187** [comment]
2022.06.23.01 Solves missing Validation icon
https://github.com/tunisiano187/WME-send-to-slack/commit/355d04b13b526e3203e1c233d1a11c8fbd8389ce

**Comment by tunisiano187** [comment]
Yes

Le dim. 10 juil. 2022 à 08:32, stale[bot] ***@***.***> a
écrit :

**Comment by EdwardNavarro** [comment]
Hi @tunisiano187 , 

I found that settings icon and tab not work because is needed to update the selectors in lines 774 and 775, please try this:

```js
$(".tabs-container ul.nav.nav-tabs").append(b);
$(".contents .tab-content").append('<div class="tab-pane" id="segment-edit-settings"><div class="settings">Slack</div></div>');
````

replace as this:

```js
$("#user-info .flex-parent #user-tabs .nav-tabs").append(b);
$("#user-info .flex-parent .tab-content").append('<div class="tab-pane" id="segment-edit-settings"><div class="settings">Slack</div></div>');
```

Other issue I got was that jQuery selectors not work if `$` variable is not declared globally, so, in this case I did it by putting following after the UserScript section (line 28), and everything works well.

```js
/* global $ */
```

**Comment by tunisiano187** [comment]
Still needs to be done

Le sam. 15 oct. 2022 à 23:39, stale[bot] ***@***.***> a
écrit :

**Comment by grosshad** [comment]
> Hi @tunisiano187 ,
> 
> I found that settings icon and tab not work because is needed to update the selectors in lines 774 and 775, please try this:
> 
> ```js
> $(".tabs-container ul.nav.nav-tabs").append(b);
> $(".contents .tab-content").append('<div class="tab-pane" id="segment-edit-settings"><div class="settings">Slack</div></div>');
> ```
> 
> replace as this:
> 
> ```js
> $("#user-info .flex-parent #user-tabs .nav-tabs").append(b);
> $("#user-info .flex-parent .tab-content").append('<div class="tab-pane" id="segment-edit-settings"><div class="settings">Slack</div></div>');
> ```
> 
> Other issue I got was that jQuery selectors not work if `$` variable is not declared globally, so, in this case I did it by putting following after the UserScript section (line 28), and everything works well.
> 
> ```js
> /* global $ */
> ```

with version 2022.08.15.01 this patch need to be applied to lines 744 and 745
