### ISSUE TITLE
[Bug] The script is not pulling updates

### ISSUE THREAD

**Issue by ordonezgs** [tunisiano187/WME-send-to-slack#86]
** add an X into between the [ ] like this [X] if you've tryied
[X] I've updated the Browser
[X] I've updated Tampermonkey/GreaceMonkey
[X] I've updated the script to the latest

**Describe the bug**
The script is not pulling updates automatically.

**Comment by tunisiano187** [comment]
Seems OK For me

**Comment by ordonezgs** [comment]
The answer seems to be here.

[StackOverFlow - Script Not Pulling Updates](https://stackoverflow.com/questions/49392803/tampermonkey-script-not-auto-updating)

Please specially note:

> Additional note to that: Once you do any change on the Editor tab and save it, the Checkbox Check for updates gets turned off.

**Comment by ordonezgs** [comment]
I will be adding some checks to prevent user. Maybe this will be mandatory for the script in order for it to work - later on...

For now.
```JS
(!GM_info.scriptWillUpdate || !GM_info.script.options.check_for_updates) ? WazeWrap.Alerts.error(SCRIPT_NAME, 'Check your TM settings... Unable to check for script updates'):undefined
```

For mandatory will be
```JS
(!GM_info.scriptWillUpdate || !GM_info.script.options.check_for_updates) ? (WazeWrap.Alerts.error(SCRIPT_NAME, 'Check your TM settings... Unable to check for script updates'), return):undefined;
```

Right at the `init()`

Also... this seems to be required by TM Docs. `@updateURL` and `@downloadURL`
