### ISSUE TITLE
[Bug] 2022.12.07.01 State value is missing after page reload

### ISSUE THREAD

**Issue by Uwe4Waze** [tunisiano187/WME-send-to-slack#93]
** add an X into between the [ ] like this [X] if you've tryied
[x] I've tryied to disable every other scripts
[x] I've updated the Browser
[x] I've updated Tampermonkey/GreaceMonkey
[x] I've updated the script to the latest

**Describe the bug**
After page reloading or opening new browser tab the previous selected state is missing.

**To Reproduce**
1. Go to https://www.waze.com/de/editor
2. Click on the settings tab
3. Select Country, State and Language-Channel
4. Reload page (F5)
5. State shows "------"

**Expected behavior**
After reloading the page the previously selected state show be preserved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.99
 - TamperMonkey

**Additional context**

**Comment by ordonezgs** [comment]
Commit pending, till 9/12/2022 UTC/GMT
